# Generated by Django 5.0.7 on 2024-08-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviereview',
            name='actors',
        ),
        migrations.RemoveField(
            model_name='moviereview',
            name='description',
        ),
        migrations.AddField(
            model_name='moviereview',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, default=1, help_text='Calificación de la película (ej. 7.5)', max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='moviereview',
            name='sinopsis',
            field=models.TextField(default=1, help_text='Sinopsis de la película'),
            preserve_default=False,
        ),
    ]
