# Generated by Django 5.0.7 on 2024-08-11 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_remove_moviereview_actors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviereview',
            name='calificacion',
            field=models.DecimalField(decimal_places=1, help_text='Calificación de la película (entre 1.0 y 10.0)', max_digits=3, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(10.0)]),
        ),
    ]
