# Generated by Django 5.0.7 on 2024-08-14 02:29

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0006_comment_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='review',
            field=tinymce.models.HTMLField(),
        ),
    ]
