# Generated by Django 5.0.7 on 2024-08-14 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0007_alter_comment_text_alter_moviereview_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='moviereview',
            name='review',
            field=models.TextField(help_text='Review del usuario'),
        ),
    ]
